version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing htmlhint..."
      - npm install -g htmlhint

  build:
    commands:
      - echo "Validating HTML..."
      - htmlhint "**/*.html"

artifacts:
  files:
    - '**/*'
